### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by diomed** [hananils/pompodium#1]
do you have any intention of updating this?

It's kinda useless. I've downloaded recently and attempted to install it to check out how some things are made,
but can't get it to work, coz all the extensions are outdated, and no longer available for this old version of Symphony.

**Comment by nilshoerrmann** [comment]
No, there are no plans to update Pompodium to the latest Symphony version. I added a note to the repository making this clear.

That said, we'd happily accept a pull request, if someone else likes to update the ensemble.

> It's kinda useless. I've downloaded recently and attempted to install it to check out how some things are made, but can't get it to work, coz all the extensions are outdated, and no longer available for this old version of Symphony.

You should still be able to install and use the ensemble.

Although the ownership of some of the extensions changed over the last 3 years, Github forwards to the updated locations correctly. You just have to make sure that you _don't update to the latest extensions' versions_ and stick to the given submodule commits.

**Comment by diomed** [comment]
I've been looking for 'date and time' for example, on symphonyextensions site,
http://symphonyextensions.com/extensions/datetime/

and this is symphony 2.3. - there are no _rollbacks _to this version.

**Comment by nilshoerrmann** [comment]
What do you mean by saying there are "no rollbacks to this version"? Version 3.1.1 of Date and Time used by this ensemble is available in the extension's repository at https://github.com/DeuxHuitHuit/datetime/releases/tag/3.1.1 for example.

Inside the [`extensions` folder of this repository](https://github.com/hananils/pompodium/tree/master/extensions) you will find links to all versions needed for the Symphony version used by Pompodium. If you clone the Pompodium repository and run `git submodule update`, all extensions will be cloned with their correct version. There should be no need to manually download any specific extension versions.

(Most of the extensions changed ownership or location over the last years, but Github will correctly forward to the updated locations.)

---

If you don't use Git but still want to install Pompodium, you'll have to download this repository and each of the extensions [as they are linked in the `extensions` folder](https://github.com/hananils/pompodium/tree/master/extensions). That should give you the compatible extension versions.

**Comment by diomed** [comment]
**Thanks for the heads up** on where is what.
Now it will be easy to find matching versions.

I appreciate it.

**Comment by nilshoerrmann** [comment]
You're welcome!
